spec/Model/DonorSpec.php
src/Model/Donor.php
src/Model/PostalAddress.php

Not sure about the data type for the last two here. Also, looking at them, I see I've mixed some languages. Shall fix.

specified data types

---

spec/Mapper/SettingsMapperSpec.php
src/Console/InitCommand.php
src/Mapper/SettingsMapper.php

The purpose of this pr is to kill bugg #11

Write to settings collection using key directly

---

spec/Builder/DateBuilderSpec.php
spec/Model/DonorState/ActiveStateSpec.php
spec/Model/DonorState/InactiveStateSpec.php
spec/Model/DonorState/MandateApprovedStateSpec.php
spec/Model/DonorState/MandateSentStateSpec.php
spec/Model/DonorState/NewDigitalMandateStateSpec.php
spec/Model/DonorState/NewMandateStateSpec.php
spec/Model/DonorState/RevocationSentStateSpec.php
spec/Model/DonorState/RevokeMandateStateSpec.php
src/Builder/DateBuilder.php
src/Console/ExportCommand.php
src/Mapper/DonorMapper.php
src/Model/DonorState/MandateApprovedState.php
src/Model/DonorState/NewDigitalMandateState.php
src/Model/DonorState/NewMandateState.php
src/Model/DonorState/RevokeMandateState.php

The goal of this pr is to solve issue #5 
Needs some work om byrokrat/autogiro first though. [DONE]
And needs pr #7 [DONE]

exporting files to autogirot

---

src/Mapper/DonorMapper.php

@nonbinary
Started work on the `MandateResponseListener` and that needs to know the donor mapper. And I know you are working on the mapper in parallel. The purpose of this pr is to define the interface of `DonorMapper` so that I can develop against the interface at the same time is you implement it.
Any comments on the interface? Hopefully we can merge this fast..

Define the donor mapper interface

---

etc/container.yaml
etc/db.yaml
spec/Listener/CommittingListenerSpec.php
spec/Listener/LoggingListenerSpec.php
spec/Mapper/SettingsMapperSpec.php
src/Console/AddCommand.php
src/Console/CommandInterface.php
src/Console/CommandWrapper.php
src/Console/ExportCommand.php
src/Console/ImportCommand.php
src/Console/InitCommand.php
src/Console/RevokeCommand.php
src/Console/StatusCommand.php
src/Events.php
src/Listener/CommittingListener.php
src/Listener/LoggingListener.php
src/Mapper/SettingsMapper.php

Fixes #21 
* Adds a `CommandWrapper` around all console commands.
* Adds a `ComittingListener` that does the committing...

Commit database on execution end

---

etc/container.yaml
spec/Event/DonorEventSpec.php
spec/Listener/MandateResponseListenerSpec.php
spec/Model/DonorState/ErrorStateSpec.php
src/Event/DonorEvent.php
src/Events.php
src/Listener/MandateResponseListener.php
src/Model/DonorState/ErrorState.php

Mandate response listener

---

src/Builder/DonorBuilder.php

Declare the state property in DonorBuilder

---

spec/Mapper/DonorMapperSpec.php
src/Mapper/DonorMapper.php

Its Collection::findOne()..

---

composer.json

Add ext-posix to composer.json

---

spec/LogFormatterSpec.php
spec/Mapper/DonorMapperSpec.php
spec/Mapper/Schema/DonorSchemaSpec.php
spec/Model/DonorSpec.php
spec/Model/PostalAddressSpec.php
src/Mapper/DonorMapper.php
src/Mapper/Schema/DonorSchema.php
src/Model/Donor.php
src/Model/PostalAddress.php

Missing tests

---

spec/Mapper/DonorMapperSpec.php
src/Console/AddCommand.php
src/Mapper/DonorMapper.php

adding a pre-existing donor throws an error

---

spec/Listener/MandateResponseListenerSpec.php
src/Listener/MandateResponseListener.php

Read info code from attribute message_id

---

composer.json
spec/DI/UserDirectoryLocatorSpec.php
src/Console/CommandWrapper.php
src/DI/ContainerFactory.php
src/DI/UserDirectoryLocator.php

A really defensive solution to close #44...

Going the extra mile to find home..

---

features/bootstrap/FeatureContext.php
features/edit.feature

Add feature test for the edit command

---

bin/giroapp
features/import.feature
features/revoke.feature
src/Console/RevokeCommand.php
src/Console/Traits/DonorArgumentTrait.php

Implement the revoke command

---

bin/giroapp
features/show.feature
src/Console/ShowCommand.php

Basic show command to display donor content..
Fixes #78.

Implement show command

---

bin/giroapp
features/ls.feature
features/plugin.feature
src/Console/LsCommand.php

Add a ls command

---

spec/Mapper/Schema/DonorSchemaSpec.php
spec/Model/DonorSpec.php
src/Console/ShowCommand.php
src/Mapper/Schema/DonorSchema.php
src/Model/Donor.php

Make donor attributable

---

spec/Builder/DonorBuilderSpec.php
src/Builder/DonorBuilder.php

Making donor attributable didn't go all the way...

Donor attributes to DonorBuilder

---

alpha1-to-alpha2.sedscript
spec/Mapper/Schema/DonorSchemaSpec.php
spec/Mapper/Schema/PostalAddressSchemaSpec.php
spec/Model/DonorSpec.php
spec/Model/PostalAddressSpec.php
src/Console/AddCommand.php
src/Console/EditCommand.php
src/Console/ShowCommand.php
src/Mapper/Schema/DonorSchema.php
src/Mapper/Schema/PostalAddressSchema.php
src/Model/Donor.php
src/Model/PostalAddress.php

close #105 
Normalizes names in `Donor` and `DonorSchema` as well as `PostalAddressSchema`.

Schema updates

---

bin/giroapp
composer.json
features/bootstrap/FeatureContext.php
features/status.feature
src/Console/StatusCommand.php
src/ProjectServiceContainer.php

Add a simple status command

---

composer.json
spec/Mapper/DonorMapperSpec.php
spec/Mapper/ExpressionToken.php
spec/Mapper/Schema/DonorSchemaSpec.php
src/Console/Traits/DonorArgumentTrait.php
src/Mapper/DonorMapper.php
src/Mapper/Schema/DonorSchema.php

Fix #25 
Defines active donor conservative as anything with a state != *INACTIVE*

Define active donor

---

etc/container.yaml
spec/Listener/OutputtingListenerSpec.php
src/Console/CommandWrapper.php
src/Listener/OutputtingListener.php
src/ProjectServiceContainer.php

Write error and warning messages to err_out

---

composer.json

Fix #106 
Checking for writability fixed in hanneskod/yaysondb@556ac7af7ced6548f2138529341510c7f2c5f850.
Seems to fix the issue when I do some unstructured testing..
Can you confirm @nonbinary?

Bumb yaysondb dependency requirement

---

composer.json
etc/container.yaml
src/Console/CommandWrapper.php
src/Console/ImportCommand.php
src/ProjectServiceContainer.php
src/Xml/XmlObject.php

Let import read stdin

---

bin/giroapp
composer.json
etc/container.yaml
etc/db.yaml
etc/fs.yaml
features/validate.feature
spec/Event/FileEventSpec.php
spec/Event/XmlEventSpec.php
spec/Listener/ImportingAutogiroListenerSpec.php
spec/Listener/ImportingListenerSpec.php
spec/Mapper/Schema/DonorSchemaSpec.php
spec/Utils/FileReaderSpec.php
spec/Utils/FileSpec.php
src/Console/ImportCommand.php
src/Console/MigrateCommand.php
src/Console/ValidateCommand.php
src/Event/FileEvent.php
src/Event/XmlEvent.php
src/Listener/ImportingAutogiroListener.php
src/Listener/ImportingListener.php
src/Mapper/Schema/DonorSchema.php
src/Mapper/Schema/donor_schema.json
src/ProjectServiceContainer.php
src/Utils/File.php
src/Utils/FileReader.php

Validate command

---

etc/container.yaml
etc/db.yaml
etc/fs.yaml
etc/listeners.yaml
spec/Listener/FileImportChecksumListenerSpec.php
spec/Listener/FileImportDumpingListenerSpec.php
spec/Mapper/FileChecksumMapperSpec.php
spec/Mapper/Schema/FileChecksumSchemaSpec.php
spec/Model/FileChecksumSpec.php
spec/Utils/FileSpec.php
src/Builder/DonorBuilder.php
src/Console/CommandWrapper.php
src/Console/ImportCommand.php
src/Events.php
src/Listener/FileImportChecksumListener.php
src/Listener/FileImportDumpingListener.php
src/Mapper/FileChecksumMapper.php
src/Mapper/Schema/FileChecksumSchema.php
src/Model/FileChecksum.php
src/ProjectServiceContainer.php
src/Utils/File.php

Will fix #36 
Missing
Makes #76 obsolete.

Collecting checksums of imported files

---

.travis.yml
TODO
behat.yml
bob_config.php
etc/container.yaml
features/bootstrap/ApplicationWrapper.php
features/bootstrap/FeatureContext.php
features/show.feature
spec/Console/Helper/QuestionFactorySpec.php
src/Console/CommandWrapper.php
src/Console/Helper/QuestionFactory.php
src/Console/Helper/Validators.php
src/Console/LsCommand.php
src/Console/ShowCommand.php
src/DependencyInjection/ProjectServiceContainer.php
src/Filter/ExportableFilter.php
src/Filter/FilterContainer.php
src/Filter/FilterInterface.php
src/Filter/InactiveFilter.php
src/Filter/NullFilter.php
src/Formatter/CsvFormatter.php
src/Formatter/FormatterContainer.php
src/Formatter/FormatterInterface.php
src/Formatter/HumanFormatter.php
src/Formatter/JsonFormatter.php
src/Formatter/TableFormatter.php

Filter n formatter
